# Generated by Django 5.1.7 on 2026-04-18 08:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='room_type',
        ),
        migrations.AlterModelOptions(
            name='facility',
            options={'ordering': ['type', 'name']},
        ),
        migrations.RenameField(
            model_name='facility',
            old_name='is_active',
            new_name='availability_status',
        ),
        migrations.RenameField(
            model_name='facility',
            old_name='max_guests',
            new_name='capacity',
        ),
        migrations.RenameField(
            model_name='facility',
            old_name='price_per_night',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='transaction_id',
            new_name='reference_number',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='guest_phone',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='guest_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='guest_name',
            new_name='valid_id',
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='facility',
            name='beds',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='features',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='size_sqm',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='subtype',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
        migrations.AddField(
            model_name='facility',
            name='type',
            field=models.CharField(choices=[('Room', 'Room'), ('Cottage', 'Cottage'), ('Pavilion', 'Pavilion')], default='Room', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='proof_of_payment',
            field=models.FileField(blank=True, null=True, upload_to='payments/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='action',
            field=models.CharField(choices=[('reservation_created', 'Reservation Created'), ('reservation_confirmed', 'Reservation Confirmed'), ('reservation_cancelled', 'Reservation Cancelled'), ('payment_verified', 'Payment Verified'), ('check_in', 'Check-in'), ('check_out', 'Check-out'), ('extension_requested', 'Extension Requested')], max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('admin', 'Administrator')], default='staff', max_length=20),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.reservation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(default='Extension', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.reservation')),
            ],
            options={
                'ordering': ['reservation', 'start_date'],
            },
        ),
        migrations.DeleteModel(
            name='RoomType',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='booking_id',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='tax_amount',
        ),
    ]
