import React, { useState, useEffect } from 'react';
import AdminSidebar from '../../components/admin/AdminSidebar';
import styles from '../../styles/AdminDashboard.module.css';
import { reservationsAPI } from '../../utils/api';
import { 
  FaCalendarAlt, FaUsers, FaChartPie, FaChartLine, 
  FaDownload, FaPlus, FaFilter, FaFileAlt 
} from 'react-icons/fa';

const AdminReports = () => {
  const [data, setData] = useState([]);
  const [showModal, setShowModal] = useState(false);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const res = await reservationsAPI.getAllReservations();
        setData(res);
      } catch (err) { console.error(err); }
    };
    fetchData();
  }, []);

  return (
    <div style={{ display: 'flex', minHeight: '100vh', background: '#f8fbff' }}>
      <AdminSidebar activePage="/admin/reports" />

      <div style={{ flex: 1, padding: '20px', overflowY: 'auto' }}>
        <header className={styles.reportHeader}>
          <h2>REPORTS</h2>
        </header>

        <div className={styles.reportGridContainer}>
          {/* --- LEFT COLUMN: ANALYTICS --- */}
          <div className={styles.analyticsColumn}>
            <section className={styles.quickReportDashboard}>
              <h3>Quick Report Dashboard</h3>
              <div className={styles.statCardsRow}>
                <div className={styles.smallStatCard}>
                  <p>Total Reservations</p>
                  <div className={styles.statMain}>
                    <strong>120</strong> <FaCalendarAlt />
                  </div>
                  <span className={styles.trendPos}>+20 last week</span>
                </div>
                <div className={styles.smallStatCard}>
                  <p>Total Guests</p>
                  <div className={styles.statMain}>
                    <strong>101</strong> <FaUsers />
                  </div>
                </div>
                <div className={styles.smallStatCard}>
                  <p>Facility Usage Breakdown</p>
                  <div className={styles.chartPlaceholder}><FaChartPie /></div>
                </div>
              </div>

              <div className={styles.graphsRow}>
                <div className={styles.graphCard}>
                  <p>Occupancy Report (Current Month)</p>
                  <h3>78.5% <small>Occupancy</small></h3>
                  <div className={styles.miniGraph}><FaChartLine /></div>
                  <button className={styles.downloadBtn}><FaDownload /> Download</button>
                </div>
                <div className={styles.graphCard}>
                  <p>Revenue Over Time (Q3 2026)</p>
                  <h3>₱145,200.00</h3>
                  <div className={styles.barGraphPlaceholder}>{/* Bar graph mock */}</div>
                  <button className={styles.downloadBtn}><FaDownload /> Download</button>
                </div>
              </div>
            </section>

            {/* Generated Reports Table */}
            <section className={styles.generatedReportsSection}>
              <div className={styles.tableHeader}>
                <h3>Generated Reports</h3>
                <button className={styles.printReportBtn} onClick={() => setShowModal(true)}>
                  <FaPlus /> Print Report
                </button>
              </div>
              <table className={styles.reportTable}>
                <thead>
                  <tr>
                    <th>Report ID</th>
                    <th>Type</th>
                    <th>Date Generated</th>
                    <th>Generated By</th>
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {[
                    {id: 'REP-001', type: 'Reservations', date: 'March 07, 2026'},
                    {id: 'REP-002', type: 'Payments', date: 'March 08, 2026'},
                    {id: 'REP-003', type: 'Facilities', date: 'March 09, 2026'},
                  ].map(report => (
                    <tr key={report.id}>
                      <td>{report.id}</td>
                      <td>{report.type}</td>
                      <td>{report.date}</td>
                      <td>Admin</td>
                      <td>
                        <button className={styles.viewLink}>View</button>
                        <button className={styles.downloadLink}>Download</button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </section>
          </div>

          {/* --- RIGHT COLUMN: FILTERS --- */}
          <aside className={styles.reportFilters}>
            <div className={styles.filterGroup}>
              <h4>Report Type</h4>
              <label>Filter by Report Type</label>
              <select><option>All Types</option></select>
              <label>Filter by Facility</label>
              <select><option>All Facilities</option></select>
              <label>Generated by</label>
              <select><option>Admin</option></select>
            </div>

            <div className={styles.filterGroup}>
              <h4>Date Range</h4>
              <div className={styles.dateTabs}>
                <button className={styles.activeTab}>Today</button>
                <button>Weekly</button>
                <button>Monthly</button>
              </div>
              <input type="date" value="2026-03-07" />
              <span>to</span>
              <input type="date" value="2026-03-10" />
            </div>

            <div className={styles.exportSection}>
              <h4>Export Report</h4>
              <label><input type="radio" checked /> Export as PDF</label>
              <label><input type="radio" /> Export as Excel</label>
              <button className={styles.generateMainBtn}>Generate Report</button>
            </div>
          </aside>
        </div>
      </div>

      {/* --- GENERATE REPORT MODAL (Matching image_968fe9) --- */}
      {showModal && (
        <div className={styles.modalOverlay}>
          <div className={styles.reportModal}>
            <div className={styles.modalHeader}>
              <h3>Generate Report</h3>
              <button onClick={() => setShowModal(false)}>&times;</button>
            </div>
            <div className={styles.modalBody}>
              <label>Report Type</label>
              <select><option>Reservations</option></select>
              <label>Facility Type</label>
              <select><option>Room 101</option></select>
              <label>Generated by</label>
              <input type="text" value="Admin" readOnly />
              <label>Date Range</label>
              <div className={styles.modalDates}>
                <input type="date" /> <span>—</span> <input type="date" />
              </div>
            </div>
            <div className={styles.modalFooter}>
              <button className={styles.cancelBtn} onClick={() => setShowModal(false)}>Cancel</button>
              <button className={styles.generateBtn}>Generate Report</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default AdminReports;